import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

import localFont from "next/font/local";

const interLocal = localFont({
  src: "/fonts/Inter.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rekrutmen BPD DIY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interLocal.className}>
        <main>{children}</main>
        <Toaster /> {/* Add the Toaster component here */}
      </body>
    </html>
  );
}
